#! /bin/sh

sxhkd &
picom &
setxkbmap -layout us,ara -variant ,digits -option grp:alt_shift_toggle caps:escape &
feh --bg-fill ~/wallpapers/wallpaper.jpg ~/wallpapers/wallpaper2.jpg &

bspc monitor HDMI-1 -d 1 2 3 4 
bspc monitor DVI-D-1 -d 5 6 7 8 

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.50

bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true 
